# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{conversation}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["David Wilkie"]
  s.date = %q{2010-05-12}
  s.description = %q{Have stateful conversations with your users over SMS, email or whichever service you like}
  s.email = %q{dwilkie@gmail.com}
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    ".gitignore",
     "MIT-LICENSE",
     "README.textile",
     "Rakefile",
     "VERSION",
     "app/models/drinking_conversation.rb",
     "app/models/sample_conversation.rb",
     "conversation.gemspec",
     "features/chatterbox.feature",
     "features/configure_blank_or_unknown_topic.feature",
     "features/configure_finishing_keywords.feature",
     "features/drinking_conversation.feature",
     "features/find_existing_conversation.feature",
     "features/find_or_create_with.feature",
     "features/retrieve_conversation_details.feature",
     "features/step_definitions/blank_unknown_topic_steps.rb",
     "features/step_definitions/chatterbox_steps.rb",
     "features/step_definitions/conversation_steps.rb",
     "features/step_definitions/drinking_conversation_steps.rb",
     "features/step_definitions/email_steps.rb",
     "features/step_definitions/pickle_steps.rb",
     "features/step_definitions/web_steps.rb",
     "features/support/env.rb",
     "features/support/paths.rb",
     "features/support/pickle.rb",
     "generators/conversation/USAGE",
     "generators/conversation/conversation_generator.rb",
     "generators/conversation/templates/chatterbox.rb",
     "generators/conversation/templates/conversation.rb",
     "generators/conversation/templates/create_conversations.rb",
     "install.rb",
     "lib/conversation.rb",
     "rails/init.rb",
     "spec/models/conversation_spec.rb",
     "spec/models/drinking_conversation_spec.rb",
     "spec/rcov.opts",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "tasks/conversation_tasks.rake",
     "uninstall.rb"
  ]
  s.homepage = %q{http://github.com/dwilkie/conversation}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Have stateful conversations with your users}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/models/conversation_spec.rb",
     "spec/models/drinking_conversation_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<state_machine>, [">= 0.9.1"])
    else
      s.add_dependency(%q<state_machine>, [">= 0.9.1"])
    end
  else
    s.add_dependency(%q<state_machine>, [">= 0.9.1"])
  end
end

